from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Document(BaseModel):
    id: str
    title: str
    domain: str
    modality: str
    summary: str
    content: str
    tags: List[str]


documents: List[Document] = [
    Document(
        id="doc-001",
        title="5G NR Handover Procedure",
        domain="RAN",
        modality="text",
        summary="Step-by-step guide for intra-frequency and inter-frequency handover in 5G New Radio networks.",
        content="The 5G NR handover procedure involves measurement configuration, measurement reporting, handover decision, and handover execution. The UE performs measurements on serving and neighbor cells based on measurement configuration from the gNB. When measurement reports trigger handover criteria, the source gNB makes a handover decision and sends a Handover Request to the target gNB via Xn interface.",
        tags=["5G", "NR", "handover", "mobility", "Xn"],
    ),
    Document(
        id="doc-002",
        title="EPC Architecture Overview",
        domain="Core",
        modality="text",
        summary="Overview of the Evolved Packet Core architecture including MME, SGW, PGW, and HSS components.",
        content="The Evolved Packet Core (EPC) consists of the MME (Mobility Management Entity) for control plane signaling, the S-GW (Serving Gateway) for user plane routing, the P-GW (PDN Gateway) for external connectivity and policy enforcement, and the HSS (Home Subscriber Server) for subscriber data.",
        tags=["EPC", "LTE", "core", "MME", "SGW", "PGW"],
    ),
    Document(
        id="doc-003",
        title="BSS Billing Reconciliation Flow",
        domain="BSS",
        modality="text",
        summary="End-to-end billing reconciliation process from CDR generation to invoice.",
        content="Call Detail Records (CDRs) are generated by the network elements and collected by the mediation platform. The mediation system normalizes, correlates, and enriches CDRs before forwarding to the rating engine. The billing system aggregates rated events into invoices.",
        tags=["BSS", "billing", "CDR", "mediation", "rating"],
    ),
    Document(
        id="doc-004",
        title="NOC Alarm Correlation Runbook",
        domain="NOC",
        modality="text",
        summary="Procedures for correlating and triaging network alarms in the Network Operations Center.",
        content="Alarm correlation reduces noise by grouping related alarms into root cause incidents. Apply temporal correlation (alarms within 30s window), then topological correlation (alarms on same physical path). Identify root cause alarm and suppress symptoms.",
        tags=["NOC", "alarms", "correlation", "SNMP", "runbook"],
    ),
    Document(
        id="doc-005",
        title="O-RAN RIC Architecture",
        domain="RAN",
        modality="text",
        summary="Open RAN Intelligent Controller architecture, near-RT and non-RT RIC components.",
        content="The O-RAN architecture introduces the RAN Intelligent Controller (RIC) in two forms: the Near-RT RIC operates on a 10ms-1s control loop, while the Non-RT RIC operates on a >1s loop for policy and ML model management. xApps run on the Near-RT RIC and rApps run on the Non-RT RIC.",
        tags=["O-RAN", "RIC", "xApp", "rApp", "open-ran"],
    ),
    Document(
        id="doc-006",
        title="VoLTE Call Flow",
        domain="Core",
        modality="text",
        summary="Voice over LTE end-to-end call setup using IMS and SIP signaling.",
        content="VoLTE call setup begins with SIP INVITE from the UE to the P-CSCF via the default EPS bearer. The P-CSCF forwards to S-CSCF which performs service triggering. A dedicated EPS bearer with QCI=1 is established for voice media using Rx/Gx interfaces.",
        tags=["VoLTE", "IMS", "SIP", "CSCF", "QCI"],
    ),
]
