/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * EveryStack API
 * Shared API contract between frontend and backend. Changes require both team approvals.
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { fetcher } from './fetcher';
export interface HealthResponse {
  status: string;
  timestamp: string;
}

export interface SearchRequest {
  /** @minLength 1 */
  query: string;
  domain?: string | null;
}

export interface SearchResultItem {
  id: string;
  title: string;
  domain: string;
  modality: string;
  summary: string;
  tags: string[];
}

export interface SearchResponse {
  query: string;
  domain: string | null;
  count: number;
  results: SearchResultItem[];
  /** Where results came from (database or mock) */
  source: string;
}

export interface UploadResponse {
  id: string;
  title: string;
  domain: string;
  s3_key: string;
  size: number;
}

export interface DomainsResponse {
  domains: string[];
}

export interface StackPackage {
  name: string;
  description: string;
}

export type StackResponseTechStack = {[key: string]: string[]};

export interface StackResponse {
  name: string;
  description: string;
  packages: StackPackage[];
  ciChecks: StackPackage[];
  techStack: StackResponseTechStack;
  uptime: number;
  pythonVersion: string;
}

export type UploadDocumentBody = {
  file: Blob;
  title: string;
  domain?: string;
  /** Comma-separated tags */
  tags?: string;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Health check
 */
export type getHealthResponse200 = {
  data: HealthResponse
  status: 200
}

export type getHealthResponseSuccess = (getHealthResponse200) & {
  headers: Headers;
};
;

export type getHealthResponse = (getHealthResponseSuccess)

export const getGetHealthUrl = () => {


  

  return `/api/health`
}

export const getHealth = async ( options?: RequestInit): Promise<getHealthResponse> => {
  
  return fetcher<getHealthResponse>(getGetHealthUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetHealthQueryKey = () => {
    return [
    `/api/health`
    ] as const;
    }

    
export const getGetHealthQueryOptions = <TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHealthQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHealth>>> = ({ signal }) => getHealth({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetHealthQueryResult = NonNullable<Awaited<ReturnType<typeof getHealth>>>
export type GetHealthQueryError = unknown


export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealth>>,
          TError,
          Awaited<ReturnType<typeof getHealth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealth>>,
          TError,
          Awaited<ReturnType<typeof getHealth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Health check
 */

export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetHealthQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Readiness check
 */
export type getReadyResponse200 = {
  data: HealthResponse
  status: 200
}

export type getReadyResponseSuccess = (getReadyResponse200) & {
  headers: Headers;
};
;

export type getReadyResponse = (getReadyResponseSuccess)

export const getGetReadyUrl = () => {


  

  return `/api/ready`
}

export const getReady = async ( options?: RequestInit): Promise<getReadyResponse> => {
  
  return fetcher<getReadyResponse>(getGetReadyUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetReadyQueryKey = () => {
    return [
    `/api/ready`
    ] as const;
    }

    
export const getGetReadyQueryOptions = <TData = Awaited<ReturnType<typeof getReady>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReady>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReadyQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReady>>> = ({ signal }) => getReady({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReady>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetReadyQueryResult = NonNullable<Awaited<ReturnType<typeof getReady>>>
export type GetReadyQueryError = unknown


export function useGetReady<TData = Awaited<ReturnType<typeof getReady>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReady>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReady>>,
          TError,
          Awaited<ReturnType<typeof getReady>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReady<TData = Awaited<ReturnType<typeof getReady>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReady>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReady>>,
          TError,
          Awaited<ReturnType<typeof getReady>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReady<TData = Awaited<ReturnType<typeof getReady>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReady>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Readiness check
 */

export function useGetReady<TData = Awaited<ReturnType<typeof getReady>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReady>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetReadyQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Template stack info
 */
export type getStackResponse200 = {
  data: StackResponse
  status: 200
}

export type getStackResponseSuccess = (getStackResponse200) & {
  headers: Headers;
};
;

export type getStackResponse = (getStackResponseSuccess)

export const getGetStackUrl = () => {


  

  return `/api/stack`
}

export const getStack = async ( options?: RequestInit): Promise<getStackResponse> => {
  
  return fetcher<getStackResponse>(getGetStackUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetStackQueryKey = () => {
    return [
    `/api/stack`
    ] as const;
    }

    
export const getGetStackQueryOptions = <TData = Awaited<ReturnType<typeof getStack>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStack>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStackQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStack>>> = ({ signal }) => getStack({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStack>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStackQueryResult = NonNullable<Awaited<ReturnType<typeof getStack>>>
export type GetStackQueryError = unknown


export function useGetStack<TData = Awaited<ReturnType<typeof getStack>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStack>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStack>>,
          TError,
          Awaited<ReturnType<typeof getStack>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStack<TData = Awaited<ReturnType<typeof getStack>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStack>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStack>>,
          TError,
          Awaited<ReturnType<typeof getStack>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStack<TData = Awaited<ReturnType<typeof getStack>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStack>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Template stack info
 */

export function useGetStack<TData = Awaited<ReturnType<typeof getStack>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStack>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStackQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Search documents
 */
export type searchResponse200 = {
  data: SearchResponse
  status: 200
}

export type searchResponse400 = {
  data: void
  status: 400
}

export type searchResponseSuccess = (searchResponse200) & {
  headers: Headers;
};
export type searchResponseError = (searchResponse400) & {
  headers: Headers;
};

export type searchResponse = (searchResponseSuccess | searchResponseError)

export const getSearchUrl = () => {


  

  return `/api/search`
}

export const search = async (searchRequest: SearchRequest, options?: RequestInit): Promise<searchResponse> => {
  
  return fetcher<searchResponse>(getSearchUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      searchRequest,)
  }
);}
  



export const getSearchMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof search>>, TError,{data: SearchRequest}, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof search>>, TError,{data: SearchRequest}, TContext> => {

const mutationKey = ['search'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof search>>, {data: SearchRequest}> = (props) => {
          const {data} = props ?? {};

          return  search(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SearchMutationResult = NonNullable<Awaited<ReturnType<typeof search>>>
    export type SearchMutationBody = SearchRequest
    export type SearchMutationError = void

    /**
 * @summary Search documents
 */
export const useSearch = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof search>>, TError,{data: SearchRequest}, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof search>>,
        TError,
        {data: SearchRequest},
        TContext
      > => {
      return useMutation(getSearchMutationOptions(options), queryClient);
    }
    
/**
 * @summary Upload a document to S3 and index in database
 */
export type uploadDocumentResponse200 = {
  data: UploadResponse
  status: 200
}

export type uploadDocumentResponseSuccess = (uploadDocumentResponse200) & {
  headers: Headers;
};
;

export type uploadDocumentResponse = (uploadDocumentResponseSuccess)

export const getUploadDocumentUrl = () => {


  

  return `/api/upload`
}

export const uploadDocument = async (uploadDocumentBody: UploadDocumentBody, options?: RequestInit): Promise<uploadDocumentResponse> => {
    const formData = new FormData();
formData.append(`file`, uploadDocumentBody.file);
formData.append(`title`, uploadDocumentBody.title);
if(uploadDocumentBody.domain !== undefined) {
 formData.append(`domain`, uploadDocumentBody.domain);
 }
if(uploadDocumentBody.tags !== undefined) {
 formData.append(`tags`, uploadDocumentBody.tags);
 }

  return fetcher<uploadDocumentResponse>(getUploadDocumentUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
);}
  



export const getUploadDocumentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadDocument>>, TError,{data: UploadDocumentBody}, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof uploadDocument>>, TError,{data: UploadDocumentBody}, TContext> => {

const mutationKey = ['uploadDocument'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadDocument>>, {data: UploadDocumentBody}> = (props) => {
          const {data} = props ?? {};

          return  uploadDocument(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UploadDocumentMutationResult = NonNullable<Awaited<ReturnType<typeof uploadDocument>>>
    export type UploadDocumentMutationBody = UploadDocumentBody
    export type UploadDocumentMutationError = unknown

    /**
 * @summary Upload a document to S3 and index in database
 */
export const useUploadDocument = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadDocument>>, TError,{data: UploadDocumentBody}, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadDocument>>,
        TError,
        {data: UploadDocumentBody},
        TContext
      > => {
      return useMutation(getUploadDocumentMutationOptions(options), queryClient);
    }
    
/**
 * @summary List available domains
 */
export type getDomainsResponse200 = {
  data: DomainsResponse
  status: 200
}

export type getDomainsResponseSuccess = (getDomainsResponse200) & {
  headers: Headers;
};
;

export type getDomainsResponse = (getDomainsResponseSuccess)

export const getGetDomainsUrl = () => {


  

  return `/api/search/domains`
}

export const getDomains = async ( options?: RequestInit): Promise<getDomainsResponse> => {
  
  return fetcher<getDomainsResponse>(getGetDomainsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetDomainsQueryKey = () => {
    return [
    `/api/search/domains`
    ] as const;
    }

    
export const getGetDomainsQueryOptions = <TData = Awaited<ReturnType<typeof getDomains>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDomains>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDomainsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDomains>>> = ({ signal }) => getDomains({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDomains>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDomainsQueryResult = NonNullable<Awaited<ReturnType<typeof getDomains>>>
export type GetDomainsQueryError = unknown


export function useGetDomains<TData = Awaited<ReturnType<typeof getDomains>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDomains>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDomains>>,
          TError,
          Awaited<ReturnType<typeof getDomains>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDomains<TData = Awaited<ReturnType<typeof getDomains>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDomains>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDomains>>,
          TError,
          Awaited<ReturnType<typeof getDomains>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDomains<TData = Awaited<ReturnType<typeof getDomains>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDomains>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List available domains
 */

export function useGetDomains<TData = Awaited<ReturnType<typeof getDomains>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDomains>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDomainsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
